


models:
  - name: gold_dim_customers
    description: Dimension table for customers
    columns:
      - name: customer_key
        description: 
        tests:            
          - not_null  
      - name: customer_id
        description: 
      - name: customer_number
        description: 
      - name: first_name
        description: 
      - name: last_name
        description: 
      - name: country
        description: 
      - name: marital_status
        description: 
      - name: gender
        description: 
      - name: birthdate
        description: 
      - name: create_date
        description: 



  - name: gold_dim_products
    description: Dimension table for products
    columns:
      - name: product_key
        description: 
        tests:            
          - not_null
      - name: product_id
        description: 
      - name: product_number
        description: 
      - name: product_name
        description: 
      - name: category_id
        description: 
      - name: category
        description: 
      - name: subcategory
        description: 
      - name: maintenance
        description: 
      - name: cost
        description: 
      - name: product_line
        description: 
      - name: start_date
        description: 





 