

models:
  - name: silver_erp_cust_az12
    description: Table silver_erp_cust_az12 is the table obtained after transforming table bronze_erp_cust_az12.
    columns:
      - name: cid
        description: 
      - name: bdate
        description: 
        tests:
          - birthdate_in_range:
              min_date: '1924-01-01'
              max_date: CURRENT_DATE
      - name: gen
        description:
      - name: dwh_create_date
        description:

  - name: silver_erp_loc_a101
    description: Table silver_erp_loc_a101 is the table obtained after transforming table bronze_erp_loc_a101.
    columns:
      - name: cid
        description: 
      - name: cntry
        description: 
        tests:
          - not_null
      - name: dwh_create_date
        description:

  - name: silver_erp_px_cat_g1v2
    description: Table silver_erp_px_cat_g1v2 is the table obtained after transforming table bronze_erp_px_cat_g1v2.
    columns:
      - name: id
        description: 
      - name: cat
        description: 
        tests:
          - no_unwanted_spaces
      - name: subcat
        description: 
        tests:
          - no_unwanted_spaces
      - name: maintenance
        description: 
        tests:
          - no_unwanted_spaces
      - name: dwh_create_date
        description:

